### ISSUE TITLE
Need option to not start health check with other services

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-webportal#1107]
I noticed a gap in our dev ops. 

When we bring up all our services we are bringing up the health checks. This means that the server could be accessible through the LB before we expect it to be. 

In Ansible we bring up the docker services, manually trigger the health checks and integration tests, and then try and enable the health checks, but the health checks are already enabled. 

We need to add an option, probably in the `docker-compose.override.yml` file to not bring the health checks up initially. This way we are in control of when they are enabled and therefore when the server goes into the LB.

**Comment by kwypchlo** [comment]
There is no gap currently, health-check marks the portal disabled before upgrading it, then after the upgrade we run the critical health checks to confirm it deployed correctly which already updates the /health-check response and only then we enable portal again. If that is not the case for some reason and upgrade script works differently, it should be fixed :)

**Comment by MSevey** [comment]
tried to repro and didn't see it
