### ISSUE TITLE
Undefined.zip when uploading folder using siasky.net

### ISSUE THREAD

**Issue by f1nasf1** [SkynetLabs/skynet-webportal#1347]
## Describe the bug
When uploading a folder into siasky.net, the folder is being saved as undefined.zip. Then when using the link to download it, it also downloads as undefined.zip

## To Reproduce
1. Go to siasky.net
2. Click on Drop any folder with an index.html file to deploy to Skynet
3. After upload, go to your uploads
4. See folder saved as undefined.zip

## Expected behavior
Folder should not be renamed undefined

## Screenshots
![image](https://user-images.githubusercontent.com/12814858/140071271-a6b83251-7c8a-4963-9aae-e8f1fc8c6b36.png)

## Version Information (please complete the following information):
 - OS: Windows 11
 - Browser: Any

**Comment by kwypchlo** [comment]
Thank you for the report, I tested on mac os and it works ok, I will have one of team members test it on windows.
