### ISSUE TITLE
Move all Airtable variables to .env file

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-webportal#1367]
## Overview
Variables defined here should all be in the .env file so portal operators don't need to edit the code base.
https://github.com/SkynetLabs/skynet-webportal/blob/master/setup-scripts/blocklist-airtable.py#L16

## Design or Proposal
Move the Base, Table, and Field to the .env file.

**Comment by kwypchlo** [comment]
But all of those are already env variables, the values that you have there are merely the defaults that we make use of.
