### ISSUE TITLE
Add comments/docs for fields in `.env`

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#1431]
## Overview

Trying to set up a portal, I was confused by all the fields in `.env`.

## Design or Proposal

There should be better comments. 

```
# Server specific
```

is not good. Neither is

```
#Handshake
```

or the total lack of comments in other places.

**Comment by ro-tex** [comment]
I believe this is already covered by the switch to ansible and the documentation we have.
