### ISSUE TITLE
`./dc` possible commands are not documented

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#1435]
## Overview

Apparently I can do `./dc up`, `./dc build` etc. but these commands are not discoverable. When I open `./dc` I see a lot of gibberish written in Bash. 

## Design or Proposal

1. Possible commands should at least be documented at the top of the file,
2. or there can be a link to a relevant document/readme.

**Comment by ro-tex** [comment]
`dc` is an augmented alias to `docker-compose`. Running the command without any parameters tells you that, as well as what commands are available within `docker-compose`.

I guess we can add a comment within the bash script which explains the extra stuff that is happening there but

**Comment by m-cat** [comment]
I had no way of knowing any of that just looking at the file.

**Comment by ro-tex** [comment]
> I had no way of knowing any of that just looking at the file.

You could have run `./dc help`, which I expect most people to do. I'm more than happy to add whatever additional docs might help people, though.
