### ISSUE TITLE
README needs an overhaul

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#1436]
## Overview

I want to start a new Skynet portal. How do I even get started? 

## Design or Proposal

1. The Readme is big and confusing and not very clear on the purpose of each section. 
1. There is a lot of terminology (Kratos, Mongo, Oathkeeper, Caddy etc. etc.) that I've never heard of.
2. I now see a `Setting up complete skynet server` section all the way at the bottom. I had no idea about this.

Perhaps instead of a giant Readme we can 
1. use the Wiki feature
2. have different pages for each topic
1. have a glossary

**Comment by ro-tex** [comment]
I believe we have a decent answer now, with the work done on https://docs.skynetlabs.com/webportal-management/overview
