### ISSUE TITLE
Lack of notification on successful operations in dashboard

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-webportal#1438]
## Describe the bug

When you log into your dashboard and go to settings you can change your email or password. Both of those actions work as expected but when you perform them there is no visual indication that the operation was successful. You click the button and nothing happens. Once again - the operations themselves are fine, the changes are made but there is no notification of that.

**Comment by kwypchlo** [comment]
new dashboard version does include success/failure notifications
