### ISSUE TITLE
Add site-map generation to the Gatsby site

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-webportal#1495]
For SEO purposes (and helping distinguish Skynet homepage from files hosted on Skynet) we should generate a sitemap with our Gatsby build.

https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/

The main complication will be making sure we include accurate "lastmod" values or Google will penalize us.

**Comment by kwypchlo** [comment]
merged in https://github.com/SkynetLabs/skynet-webportal/pull/1544
