### ISSUE TITLE
The portal does not redirect to 404.html

### ISSUE THREAD

**Issue by wuniversales** [SkynetLabs/skynet-webportal#1576]
Hi, I'm telling you, my static website does not load the 404 error even though I have a file called 404.html in the root of the website.
Does the portal not redirect 404 errors?
I leave you the website where I have the problem.
https://rapidleecher.eu.org/does-not-exist
https://rapidleecher.eu.org/404.html
Thanks greetings

**Comment by kwypchlo** [comment]
This is your upload metadata: https://siasky.net/skynet/metadata/fAXBznlXH1Yo3csgOFe3qPnuFDAJxnEJVygpM7GmGvTaPQ

You are missing error pages declaration. If you're using skynet-js it's available in the latest v4 beta release. If you're using [deploy to skynet action](https://github.com/SkynetLabs/deploy-to-skynet-action) then you can use [not-found-page](https://github.com/SkynetLabs/deploy-to-skynet-action#not-found-page). It should point to your 404.html file.

Feel free to join skynet discord to reach out for help if you're still having issues after that.

**Comment by wuniversales** [comment]
Searching for information and talking to users I have found the problem, maybe it would be good to open this issue again...
The problem is that I upload the web from.
https://siasky.net
And apparently from the web you can not edit that metadata.

Could you put the default address "skynet-404.html" for 404 errors?
There are people like me who don't want to complicate life with metadata, and simply use siasky.net to upload the web.

I suggest that by default the web portal uses, as in the case of ipfs, a default address in which to show 404 errors.

As in ipfs it is "ipfs-404.html", I suggest that for skynet it is the default "skynet-404.html" for all the webs that are sent from siasky.net

Thanks greetings

**Comment by kwypchlo** [comment]
Thanks @wuniversales for the input, I created an appropriate issue where we'll discuss a best way to remedy the situation.
