### ISSUE TITLE
Remove nginx cache directory from docker compose

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-webportal#2001]
## Overview
We have moved the cache to skyd.

## Design or Proposal
Since we moved the cache to skyd, I assume we don't need to create/define a cache directory in the nginx docker compose file anymore right?

https://github.com/SkynetLabs/skynet-webportal/blob/master/docker-compose.yml#L66

**Comment by ro-tex** [comment]
Should we also add some sort of a sweeper that removes it from disk?
We have accumulated some garbage there - leftovers from kratos/oathkeeper/cockroachdb, now nginx cache as well.
I don't think it's a big deal but it will reclaim some disk space and it keeps the systems tidy.

**Comment by kwypchlo** [comment]
We still use nginx cache for caching responses unrelated to skylinks like /skynet/portals or /skynet/stats endpoints.
