### ISSUE TITLE
Directory drag-and-drop on Firefox does not preserve Content-Type

### ISSUE THREAD

**Issue by max-was-here** [SkynetLabs/skynet-webportal#290]
There is an issue on Firefox where drag-and-dropping a directory for upload will lose all files Content-type. Files will be incorrectly uploaded with the content-type `application/octet-stream`   
Tested on Firefox 78.0.1 on MacOS but also reported to happen on Windows from another user on Discord.

### Steps to reproduce
 
1. Put 1 or more images of standard mime type file in a folder (jpg, png...)
2. Drag-and-drop the folder in the Drop zone in a Firefox browser
3. Once uploaded, click on the generated Skylink. The browser will download the image instead of displaying it because of improper mime type

### Things to consider

* The bug only happens on drag-and-drop. Clicking on the zone and selecting the directory will keep the proper mime-type
* The bug happens whether the dropzone is in "File mode" or "Directory mode". But will only happen when drag-and-dropping a directory from the file system.
* This happens because the content type is `application/octet-stream` during the multipart upload (so it's an upload issue)

### Progress

I tried digging down and find the source of the bug, from my findings it might be an issue with Firefox itself, and I could not find any workaround.  
I first dug into the [react-dropzone](https://github.com/react-dropzone/react-dropzone) dependency to understand how it was managing dropped directories, only to find that [it was using a sub-dependency](https://github.com/react-dropzone/react-dropzone/blob/v11.0.1/src/index.js#L361).  
And when digging down into [file-selector](https://github.com/react-dropzone/file-selector) I found out that it converts the [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/DataTransfer) from the 'drop' event into files using [FileSystemFileEntry.file()](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/file). Using that method leaves the File.type empty on Firefox.

From there I tried to workaround that limitation a bit or find another way to get the files with mime type from the drop event, with no success. It's all the time I had today to work on this but I wanted to document the issue and my progress here so someone or I can pick it up later.

### Conclusion + possible solution

So right now it mostly seems like a bug with Firefox `FileSystemFileEntry`, other drag-and-drop library might have the exact same problem as it seems like the standard way to manage drag-and-drop uploads right now.

A possible solution would be to use another library like [mime-types](https://github.com/jshttp/mime-types) or [mime-db](https://github.com/jshttp/mime-db) to detect the files mime-type when the `File.type` attribute is empty. But I'm not sure if we can manually change the Content-type in a multipart upload after that.

**Comment by max-was-here** [comment]
Hey, thanks for the fix! Looks like it solves the problem partially though. It works for some files like images but not other types like html files.

That's because when doing a folder drag-and-drop, Firefox leaves the File.type empty, but some file types are detected by [file-selector](https://github.com/react-dropzone/file-selector). See the [COMMON_MIME_TYPES here](https://github.com/react-dropzone/file-selector/blob/v0.1.12/src/file.ts#L1). If a file is not one of those, like a HTML file, the fix implemented won't work since the File.type will be left empty.

They have [this issue](https://github.com/react-dropzone/file-selector/issues/25) that points to some mime types libraries for detection. Do you think it would be better to implement this type of mime detection in skynet-js code?

**Comment by kwypchlo** [comment]
@max-was-here good catch, I actually tested that only on various images. Looks like file-selector could use https://github.com/jshttp/mime-types as a dependency instead of their very limited extension map. 
Ideally, I would suggest we create a PR to file-selector and replace their map with the dependency you've found to make sure the extension list is exhaustive. If you feel comfortable doing it, let me know, otherwise I can prepare the PR.
In the meantime, we could add that dependency to skynet-js and detect the mime type ourselves if it's empty. We could then roll back once the proper fix in file-selector is merged. PR for that would be most welcomed :) https://github.com/NebulousLabs/skynet-js/blob/master/src/upload.js#L55-L64 this is the function that would have to be extended to detect the type if it's missing.

**Comment by kwypchlo** [comment]
Not an issue any more it seems, just tried to recreate with newest Firefox and all skylinks are working fine:

Folder upload with aaa.jpeg and bbb.png
https://fg07gpachs91gjkoc92co7e9addvbr3nrrgmrq6m528lup87hpd9flg.siasky.net/aaa.jpg
https://fg07gpachs91gjkoc92co7e9addvbr3nrrgmrq6m528lup87hpd9flg.siasky.net/bbb.png

Files upload aaa.jpeg and bbb.png uploaded by dragging the folder with files inside
https://siasky.net/nAFDm0tAH24LnJ2jDBzlFTChHVbyuzJxO_5nCn4JB7jzuw
https://siasky.net/PAARf9-MoGBWVTwDbzVRxTYUhhsmwOnwAvrklTdE31dAyw
