### ISSUE TITLE
Health Check Extension

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-webportal#348]
# Health Check Extension

## Overview
The Health Check for the portals needs to be extended in order to provide better coverage to catch bugs on upgrades. 

The current health check is a simple upload and download of a file that runs every 5 minutes. The plan would be to expand upon this as well as add a daily set of checks.

## Goals
The Goals of Expanding the Health Checks are:
1. Ability to catch bugs before deploying new code to servers
2. Ability to catch compatibility bugs
3. Increase scope of Health Checks for better ongoing coverage
4. Extendable

### Basic Checks
The current health check will be referred to as the `Basic Checks` and will continue to run every 5 minutes. These will undergo the following updates:
1. Add Upload/Download of Directory
2. Add Upload/Download of an Application
3. Add handling of redirects (ie no trailing slash, trailing slash, HNS, `/index.html)

### Critical Checks
The results of the Health Checks are currently stored as JSON entries in a DB. The plan will be to extend this JSON entry and have a `Critical` field. To allow for a wider range of checks, this `critical` field will be used to determine which checks should result in portals being taken offline if there are failures. 

### Compatibility Checks
To help ensure we are not breaking compatibility with any content already on Skynet we will have a list of known skylinks that are under our control. For all these skylinks we will have backups of the actual files that were uploaded. The metadata and the body content will be verified.

**Comment by MSevey** [comment]
Skylinks to add:
**Uniswap**  
- `hns/doesn`
- `hns/doesn/`
- `hnsres/doesn`
- `hnsres/doesn/`
- `IAC6CkhNYuWZqMVr1gob1B6tPg4MrBGRzTaDvAIAeu9A9w`
- `IAC6CkhNYuWZqMVr1gob1B6tPg4MrBGRzTaDvAIAeu9A9w/`

**Develop Momentum**  
- `EAA1fG_ip4C1Vi1Ijvsr1oyr8jpH0Bo9HXya0T3kw-elGw'
- `EAA1fG_ip4C1Vi1Ijvsr1oyr8jpH0Bo9HXya0T3kw-elGw/'

**Example Video on siasky.net**  
-`CABAB_1Dt0FJsxqsu_J4TodNCbCGvtFf1Uys_3EgzOlTcg`

**Comment by MSevey** [comment]
Add endpoint for all results

https://github.com/NebulousLabs/skynet-webportal/pull/330#discussion_r476517050

**Comment by DavidVorick** [comment]
Karol mentioned that we are checking the response body results by looking at the hash and comparing it to an expected hash. This isn't going to work because future versions of the portal may add additional fields to the response, and that is not a breaking change. What we need to do is verify that all the fields that existed previously still exist and have the expected values.

Bit more work than a hash, but will make the test more robust as we add fields in the future.

**Comment by MSevey** [comment]
@DavidVorick 

> Karol mentioned that we are checking the response body results by looking at the hash and comparing it to an expected hash. This isn't going to work because future versions of the portal may add additional fields to the response, and that is not a breaking change. What we need to do is verify that all the fields that existed previously still exist and have the expected values.
> 
> Bit more work than a hash, but will make the test more robust as we add fields in the future.

We updated the check to check a hash of the body blob, since that is that actual file data and shouldn't change.

Then for the metadata we are currently comparing the json objects so we have a saved expected version. 

The question is, how do we want to extend these checks over time? If we are adding fields to the metadata, do we want the health checks to fail, informing us that there were changes and then we can see what the changes were and decide if we need to update the health check of fix a compatibility bug?  If so I believe the current set up will do that. 

If we only check for currently expected fields then we will miss understanding how new metadata fields impact existing skylinks/skyfiles.

**Comment by kwypchlo** [comment]
We should also check on every link:
- status code
- headers: location, content-type, content-disposition

We should add tests for:
- not existing skylink
- not existing hns domain (test /hns and /hnsres)

Most importantly, we need to check whether the skylink returns 200 or 307. I don't know if superagent follow redirects by default or not so this is something we need to investigate. We should have a test suite that tests the 307 redirects, all cases.

**Comment by MSevey** [comment]
Need to incorporate checks for subdomains and prefix handling

**Comment by kwypchlo** [comment]
outdated, extended health checks has been already implemented for a while
