### ISSUE TITLE
Not seeing content-type in response header in Firefox

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#566]
For example, trying this:

https://sky-bin.hns.siasky.net/

I don't see the content-type in Firefox:

<img width="532" alt="Screen Shot 2020-12-14 at 14 54 20" src="https://user-images.githubusercontent.com/6035856/102089382-07704b80-3e14-11eb-8811-89aee6914f58.png">

Whereas it is present in Brave:

<img width="470" alt="Screen Shot 2020-12-14 at 14 54 43" src="https://user-images.githubusercontent.com/6035856/102089365-02130100-3e14-11eb-9311-ffeb6e82c1b3.png">

Not sure if this is an issue or not but I thought it was weird.

**Comment by kwypchlo** [comment]
This is not an issue but rather how 304 works in browsers

https://stackoverflow.com/questions/31099113/why-response-304-doesnt-have-content-type-header

"no cache" enabled, 200 OK - content type present
<img width="550" alt="Screenshot 2022-09-13 at 13 07 52" src="https://user-images.githubusercontent.com/3755029/189886159-34daa1e8-d289-4bf4-9671-896c0ac6c911.png">

"no cache" disabled, 304 Not Modified - content type **not** present
<img width="551" alt="Screenshot 2022-09-13 at 13 08 13" src="https://user-images.githubusercontent.com/3755029/189886227-2df70f23-a6ce-43aa-bcec-d0ce9c3f7e54.png">
