### ISSUE TITLE
Certain "special" dirs need to be documented or disabled for HNS subdomains

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#568]
API endpoints and other special url structures over-ride skapp resolution.

For example, this url should point to the index.html file of the docs folder on my app (even if it doesn't actually exist), but instead loads the SDK Docs:  `https://oklacity.hns.siasky.net/docs/index.html#introduction`

From https://app.gitbook.com/@skynet-labs/s/sdks/future-sdk-plans/developer-interview-feedback#web2-static-conventions

**Comment by dhelma** [comment]
We need to be careful for things like `/registry/` since SDK libs send requests to the subdomain-ed endpoint.

**Comment by kwypchlo** [comment]
taken care of in https://github.com/SkynetLabs/skynet-webportal/pull/719
