### ISSUE TITLE
502 Bad Gateway error when loading a skylink that contains index.html

### ISSUE THREAD

**Issue by harej** [SkynetLabs/skynet-webportal#574]
Steps to reproduce:

1) Go to https://siasky.net/fAVLKgqZjAkzfvFLHskFp9KgDMHM1FNsWJENxyKvhQ9PDg/

2) See error "502 Bad Gateway"

3) Add "index.html" to the URL

4) Page loads normally

**Comment by harej** [comment]
Here is a zipped version of that skylink https://siasky.net/AACt69W4S5CFUgM6PF4SL6jaKOy6Q5fNQ9gi_39O-qfceQ

**Comment by harej** [comment]
Now getting the error upon uploads as well:

<img width="705" alt="Screen Shot 2020-12-25 at 2 13 41 PM" src="https://user-images.githubusercontent.com/150027/103142651-85a5db00-46bb-11eb-8324-8b13428e121f.png">

**Comment by kwypchlo** [comment]
resolved by a breaking change in skyd that removes file metadata from header, the example link works now
