### ISSUE TITLE
Skynet Stats to include Maintenance Servers

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skynet-webportal#579]
As we rotate out production servers to maintenance servers we need to make sure that the stats information is still being reported. 

Additionally we should have `https://siasky.net/skynet/stats` return stats for all servers so that `siastats.info` doesn't need to keep a list of all our server names and ping them individually.

**Comment by kwypchlo** [comment]
There is already a code in place to include those stats https://github.com/NebulousLabs/skynet-webportal/pull/562
I will backfill the numbers today 👍

**Comment by kwypchlo** [comment]
That code can be removed now since we're aiming at having one skyd node per address right now.
