### ISSUE TITLE
Provide endpoint to resolve registry url to skylink

### ISSUE THREAD

**Issue by themailman05** [SkynetLabs/skynet-webportal#609]
Hello,

I would like to use SkyDB as off-chain storage for tokenURI metadata in an ERC721 token.
In order to do so, I need a piece of infra which can resolve a registry URL i.e. 

[https://note-to-self.hns.skyportal.xyz/skynet/registry?publickey=ed25519%3A4c2cc8b62ebf86cce7519c8d2e0c0ed71a274a22194ac504c99b2ebc761222ef&datakey=79c05b4b67764ad99a7976a7d2fb1cfce4f196ea217ef0356af042cb5492bd5d](https://note-to-self.hns.skyportal.xyz/skynet/registry?publickey=ed25519%3A4c2cc8b62ebf86cce7519c8d2e0c0ed71a274a22194ac504c99b2ebc761222ef&datakey=79c05b4b67764ad99a7976a7d2fb1cfce4f196ea217ef0356af042cb5492bd5d)

to the actual json data stored at the embedded skylink location

I am planning to build a middleware service that does these requests using `skynet-client.js`, but it would be nice to have this built into the portal API itself.

The request would look something like: `GET skynet/skydb/publickey=ed25519%3A4c2cc8b62ebf86cce7519c8d2e0c0ed71a274a22194ac504c99b2ebc761222ef&datakey=my_awesome_data_key` and would return `{key:value}` in UTF-8 JSON string

Updating the data could still happen clientside for now. I don't need to set skydb entries with HTTP yet, just retrieve the JSON.

This way, I can have an off-chain, mutable, but still decentralized metadata store.

**Comment by themailman05** [comment]
Maybe this could be part of the new websockets API instead
That is what I really need anyhow.

**Comment by themailman05** [comment]
Might try to hack on this if it isn't high priority for the core team right now. Would really like this feature.

**Comment by kwypchlo** [comment]
cleaning up outdated issue, this functionality is already supported via resolver skylinks that are basically encoded registry entries
