### ISSUE TITLE
Using Domain Name CNAME & TXT records to serve webapps

### ISSUE THREAD

**Issue by dghelm** [SkynetLabs/skynet-webportal#636]
Many users ask how to host on Skynet behind `mydomain.com` -- 

One solution could be taking a book from IPFS's structure, where DNS records on an arbitrary domain look like this:

CNAME record: @, gateway.url
TXT record: dnslink=/rest/of/url/

Their implementation to do this is pretty straight forward:
https://github.com/ipfs/go-dnslink/blob/master/dnslink.go

My first guess is to set up odd wildcards for possible hostnames:
http://nginx.org/en/docs/http/server_names.html

I'd assume we'd just want to keep HNS defaults for `skyns:` and `sia:`. TLS would likely be a complex problem unless [this Caddy feature](https://caddyserver.com/docs/automatic-https#on-demand-tls) works for the wildest of wildcards.

**Comment by kwypchlo** [comment]
we've implemented that already
