### ISSUE TITLE
base32 HNS subdomains are working when they shouldn't be

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#643]
Take the following base32 link:

https://vg53pu9te201d082do0g5q2ji9qsk31dfpf01men3p8ak6ae0j8toeg.siasky.net/

Due to a bug in the SDK we added `.hns`, which still worked:

https://vg53pu9te201d082do0g5q2ji9qsk31dfpf01men3p8ak6ae0j8toeg.hns.siasky.net/

This feels like a bug. I'm guessing there's a regex or something that sees a valid base32 skylink and accepts it. There *may* be an issue if someone hijacks that actual HNS domain, though it feels like the portal isn't checking HNS here.

Note that this *doesn't* work (good):

https://siasky.net/hns/vg53pu9te201d082do0g5q2ji9qsk31dfpf01men3p8ak6ae0j8toeg

**Comment by kwypchlo** [comment]
resolved in https://github.com/SkynetLabs/skynet-webportal/pull/719
