### ISSUE TITLE
Keep users logged in until they log out

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-webportal#658]
### Done

We need the cookies (and JWT tokens, respectively) to last significantly longer than 24 hours. That is already changed to be 30 days in https://github.com/NebulousLabs/skynet-webportal/commit/eefc733ec86a904546f7d4c484f7d5970bd32fb8.

### To do

The above is still insufficient as the user might not login/logout each 30 days and they might not notice that their cookie has expired. For that we need the portal to actively monitor the age of the cookie and redirect to `accounts`'s `/login` endpoint if the cookie has less than 29 days to live. That will ensure that we'll keep users' cookies fresh.

Afaik, this cannot be handled directly in `accounts`, as the user's browser is not redirected to `accounts` during normal skapp usage.

**Comment by kwypchlo** [comment]
resolved by https://github.com/SkynetLabs/skynet-accounts/pull/124
