### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-webportal#702]
Doesn't this work?
```suggestion
servers=(  "eu-ger-1.siasky.net" "eu-ger-2.siasky.net" "eu-ger-3.siasky.net" "eu-ger-4.siasky.net"
```

_Originally posted by @m-cat in https://github.com/SkynetLabs/skynet-webportal/pull/697#r621193797_

**Comment by kwypchlo** [comment]
not relevant any more, the line in question has been removed
