### ISSUE TITLE
Support Range HTTP request header for partial downloads

### ISSUE THREAD

**Issue by jay-dee7** [SkynetLabs/skynet-webportal#775]
Hey guys I was recently exploring the different ways to download files from skynet and I realized that the SDKs didn't have a way to add the `Range` http header into the requests which can be used to retrieve a partial file. Range header basically is like an offset value that we can use to let the server know what parts we're interested in.

Here's a reference to this header information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by dghelm** [comment]
So I misinformed you yesterday! This is totally supported by our portals by using Range headers like here where just half of the file size is requested:
![Partial Download Request](https://siasky.net/ZABKTfhaRLTQQsHgmVKVBDzhquRAJ0Cl7od_OodbZZwXpA)
