### ISSUE TITLE
Implement a SkyDB storage plugin for Caddy

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-webportal#782]
## Overview

We need a plugin that allows Caddy to use SkyDB as storage for its certificates generation on fleet level.

## General Plan
The current plan is to fork and adapt https://github.com/silinternational/certmagic-storage-dynamodb. We will need to add a couple of complications in order to implement some parts (e.g. List functionality) but it should be very much doable and still performant enough.

## Step-by-step

* The fork is at https://github.com/SkynetLabs/certmagic-storage-skydb
* One complication that we noticed during the initial scan was that this plugin has a "list" operation which we don't have in SkyDB. In order to accommodate that we'll have a reference to a list of all operations performed by the plugin for a given identity. That list will be referenced by each record and extended on each operation.

TBD

**Comment by kwypchlo** [comment]
why is this https://github.com/SkynetLabs/certmagic-storage-skydb not a fork?

![Screenshot 2021-05-26 at 18 05 39](https://user-images.githubusercontent.com/3755029/119693976-18a29700-be4d-11eb-9a37-eef41572cec1.png)

Usually forks do have that indication on them ie:

![Screenshot 2021-05-26 at 18 06 36](https://user-images.githubusercontent.com/3755029/119694014-20fad200-be4d-11eb-839c-977248c90a2b.png)
