### ISSUE TITLE
Add query parameters for byte ranges to skynet download links 

### ISSUE THREAD

**Issue by BoySanic** [SkynetLabs/skynet-webportal#937]
While currently there are HTTP headers that can be used to request particular byte ranges from a file, it would be useful to have such an option baked into the URL.

As discussed in Discord, our project (Minecraft@Home) cannot adjust the HTTP headers since we must use BOINC's framework to request those files, and at most they allow us to specify the URL.

This feature would greatly help us move forward in our current project, and potentially again in the future!

Something like...

https://siasky.net/_ACaZbb_HBp3Iq_zAGNBd_GHU2r8L8ykJ-K9c7zxn_KMUA?byterange=0-2400

(As an example)

Please let me know if you have any questions.

**Comment by kwypchlo** [comment]
That's a good request but since this only applies to a download, we could potentially consider it for a /file endpoint:
https://siasky.net/file/_ACaZbb_HBp3Iq_zAGNBd_GHU2r8L8ykJ-K9c7zxn_KMUA?byterange=0-2400

**Comment by BoySanic** [comment]
Yep, I think adding it to the /file endpoint would work for our needs.

I mostly provided that url as an example, there wasn't anything specific to that url other than the query at the end that mattered for this request to be useful to us.

Thanks!

**Comment by kwypchlo** [comment]
> Yep, I think adding it to the /file endpoint would work for our needs.
> 
> I mostly provided that url as an example, there wasn't anything specific to that url other than the query at the end that mattered for this request to be useful to us.
> 
> Thanks!

Hey @BoySanic you should be now able to use byte ranges in query params, please use /file endpoint - query params are "start" and "end"

https://siasky.net/file/CACqf4NlIMlA0CCCieYGjpViPGyfyJ4v1x3bmuCKZX8FKA/?start=200&end=500

**Comment by kwypchlo** [comment]
I'm going to go ahead and close this, let me know if there are any issues with the implementation.
